'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { loadMergedMemoryConfig } = require('./config.cjs');

/**
 * @param {string} abs
 * @param {number} maxChars
 */
function readCapped(abs, maxChars) {
  if (!fs.existsSync(abs)) return null;
  let s = fs.readFileSync(abs, 'utf8');
  if (s.length > maxChars) {
    s = `${s.slice(0, Math.max(0, maxChars - 40))}\n\n… (truncated)\n`;
  }
  return s;
}

/**
 * Deterministic merge of key work-item markdown files into one capped artifact (no LLM).
 * @param {{ workDirAbs: string, pluginRoot: string }} opts
 * @returns {{ markdown: string, outputPath: string, filesUsed: string[] }}
 */
function buildCompactArtifact(opts) {
  const workDir = path.resolve(opts.workDirAbs);
  const pluginRoot = path.resolve(opts.pluginRoot);
  const projectRoot = path.resolve(workDir, '..', '..');
  const merged = loadMergedMemoryConfig(pluginRoot, projectRoot);
  const compact = merged.compact || {};

  const names =
    Array.isArray(compact.include_names) && compact.include_names.length > 0
      ? compact.include_names
      : ['progress.md', 'design.md', 'feasibility.md', 'implementation.md'];
  const maxFile =
    compact.max_chars_per_file != null ? Number(compact.max_chars_per_file) : 8000;
  const maxTotal =
    compact.max_total_chars != null ? Number(compact.max_total_chars) : 24000;
  const outName =
    typeof compact.output_filename === 'string' && compact.output_filename.length > 0
      ? compact.output_filename
      : 'context-compact.md';

  const lines = [];
  lines.push('# Context compact (deterministic)');
  lines.push('');
  lines.push(
    '_Generated by `memory-compact`: concatenation with per-file and total caps; not a substitute for `progress.md`._'
  );
  lines.push('');

  let total = 0;
  const used = [];
  for (const name of names) {
    const abs = path.join(workDir, name);
    const text = readCapped(abs, Math.min(500000, Math.max(256, maxFile)));
    if (text == null) continue;
    const blockLen = text.length + 80;
    if (total + blockLen > maxTotal) {
      lines.push('_Stopped: max_total_chars budget reached._');
      lines.push('');
      break;
    }
    total += blockLen;
    used.push(name);
    lines.push(`## ${name}`);
    lines.push('');
    lines.push(text);
    lines.push('');
  }

  const outputPath = path.join(workDir, outName);
  return { markdown: lines.join('\n'), outputPath, filesUsed: used };
}

/**
 * @param {{ workDirAbs: string, pluginRoot: string }} opts
 * @returns {{ outputPath: string, filesUsed: string[] }}
 */
function writeCompactArtifact(opts) {
  const r = buildCompactArtifact(opts);
  fs.writeFileSync(r.outputPath, r.markdown, 'utf8');
  return { outputPath: r.outputPath, filesUsed: r.filesUsed };
}

module.exports = {
  buildCompactArtifact,
  writeCompactArtifact,
};
